### ISSUE TITLE
Build a new website for the team

### ISSUE THREAD

**Issue by zanealoia** [fairviewrobotics/blackknightsrobotics-site#1]
We will be working closely with the operations subteam to develop a new website for the team. This website should be in a new repository so that future members can update the website as long as they have access to the Github. People working on this project should work together to finish the website while also focusing on UI. This website will be a model of the team that we send out to people who are interested, so it should work consistently well.

**Comment by zanealoia** [comment]
Our site domain name is blackknightsrobotics.org. We have an SSL certificate from Google that is waiting to be implemented. I am looking into Vercel.

**Comment by aaditsangvikar** [comment]
Vercel implemented, SSL certificate attached.
