### ISSUE TITLE
Find new domain

### ISSUE THREAD

**Issue by aaditsangvikar** [fairviewrobotics/blackknightsrobotics-site#2]
We might still own fairviewrobotics.org, but since we are no longer directly affiliated with Fairview, we should look for a different domain... blackknightsrobotics.org, .com, etc?

**Comment by zaneal** [comment]
Domain found. SSL certificate also comes with that purchase, it will just need to be implemented.

**Comment by zanealoia** [comment]
Domain found. SSL certificate also comes with that purchase, it will just need to be implemented.
